name: CI Pipeline

on:
  push:
    branches:
      - v2

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.0]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ vars.PGUSER }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
          POSTGRES_DB: ${{ vars.PGDATABASE }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      CI: true
      HOST: ${{ vars.HOST }}
      PORT: ${{ vars.PORT}}
      PGHOST: ${{ vars.PGHOST }}
      PGPORT: ${{ vars.PGPORT }}
      PGUSER: ${{ vars.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ vars.PGDATABASE }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      ACCESS_TOKEN_AGE: ${{ vars.ACCESS_TOKEN_AGE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js dependencies
        run: npm install

      - name: Run database migrations
        run: npm run migrate up

      - name: Run tests
        run: npm run test
