name: Continuous Integration

on:
  push:
    branches:
      - v2

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_DB: forumapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        env:
          DATABASE_URL: postgres://postgres:secretpassword@localhost:5432/forumapi
        run: npm run migrate up

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:secretpassword@localhost:5432/forumapi
        run: npm run test
